server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: corporate-climber

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/corporate_climber?useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  sql:
    init:
      mode: never

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  h2:
    console:
      enabled: false

gemini:
  api:
    key: ${GEMINI_API_KEY}
    base-url: ${GEMINI_BASE_URL:https://generativelanguage.googleapis.com/v1beta}

google:
  credentials:
    path: ${GOOGLE_CREDENTIALS_PATH}

logging:
  level:
    com.corpclimb: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
